import pandas as pd
import matplotlib.pyplot as plt
"""
scatter plot of the data generated by smn_analysis.py
"""
df = pd.read_csv("c_count.tsv", sep='\t')
SMN_C_count = df['SMN c.840: Reads with C']
SMN_total = df['SMN c.840: Total Reads']
x = list(SMN_C_count)
y = list(SMN_total)
plt.scatter(x=x,y=y,color = 'b')
plt.grid(True)
plt.xlabel('SMN c.840: Reads with C')
plt.ylabel('SMN c.840: Total Reads')
plt.title('SMN c.840: Reads with C vs SMN c.840: Total Reads')
plt.savefig('C_vs_total.png')
